Repository sopel-irc/sopel-youtube, pull requests merged in 2020-05, with the labels that each got.

#20 Work around Google/YouTube bad timestamp data
  sopel_modules/youtube/youtube.py
Labels: bugfix

#18 Add output formatting options
  sopel_modules/youtube/youtube.py
Labels: enhancement, tweak

#21 Remove YouTube Logo Colors
  sopel_modules/youtube/youtube.py
Labels: tweak
